config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'articles#index'
  devise_for :users
  resources :users, only: [:show]
  resources :articles do
    resources :likes, only: [:create, :destroy]
    collection do
      post :confirm
    end
  end
  resources :favorites, only: [:create, :destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  self.inheritance_column = :_type_disabled
  mount_uploader :image, ImageUploader
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes,source: :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates_uniqueness_of :article_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :articles, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_articles, through: :favorites, source: :article
  has_many :likes, dependent: :destroy
  has_many :like_articles, through: :likes, source: :article
  enum sex: {unanswered: 0, male: 1, female: 2}
  enum prefectures: {
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
    沖縄県:47
  }

  def age
    user_birthday = self.birthday
    today = Date.today.strftime("%Y%m%d").to_i
    birthday = user_birthday.strftime("%Y%m%d").to_i
    user_age = (today - birthday) / 10000
    if user_age < 10
      10
    else
      user_age.floor(-1)
    end
  end

  def liked_by?(article_id)
    likes.where(article_id: article_id).exists?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :prefectures, :birthday, :sex])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :prefectures, :birthday, :sex, :image, :image_cache, :introduction, :twitter_url, :instagram_url, :tiktok_url, :facebook_url, :youtube_url, :website_url])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new edit update destroy]
  
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if params[:back]
      render :new
    else
      if @article.save
        redirect_to articles_path, notice: "記事を作成しました"
      else
      render :new
      end
    end
  end

  def show
    if user_signed_in?
      @favorite = current_user.favorites.find_by(article_id: @article.id)
      @like = current_user.likes.find_by(article_id: @article.id)
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path, notice: "記事を編集しました"
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path, notice: "記事を削除しました"
  end

  def confirm
    @article = current_user.articles.build(article_params)
    render :new if @article.invalid?
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :image, :image_cache, :type)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy index]

  def create
    favorite = current_user.favorites.create(article_id: params[:article_id])
    redirect_to articles_path, notice: "#{favorite.article.user.name}さんの記事をお気に入りしました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to articles_path, notice: "#{favorite.article.user.name}さんの記事をお気に入り解除しました"
  end

  def index
    @favorites = current_user.favorite_articles.order(created_at: :desc)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :set_article

  def create
    Like.create(user_id: current_user.id, article_id: params[:article_id])
  end

  def destroy
    Like.find_by(user_id: current_user.id, article_id: params[:article_id]).destroy
    redirect_to article_path(@article)
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_age = @user.age
    @articles = @user.articles.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_articles_path
    elsif action_name == 'edit'
      article_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true, url: choose_new_or_edit ) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= @article.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="article_type">
    <%= f.label :type %>
    <%= f.select :type, [["記事", 0],["質問", 1]] %>
  </div>
  <div class="article_image">
    <%= f.label :image %>
    <%= image_tag(@article.image.url) if @article.image && @article.image.url %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="article_title">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="article_content">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <%= f.submit %>
<% end %>
<%= link_to 'ブログ一覧画面に戻る', articles_path %>

app/views/articles/confirm.html.erb
<h3>以下の内容で、投稿します</h3>

<%= form_with(model: @article, local: true, url: articles_path ) do |f| %>
  <%= f.hidden_field :type %>
  <%= f.hidden_field :image %>
  <%= f.hidden_field :image_cache %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>

  <p>記事種類：<%= @article.type %></p>
  <p>写真：<%= image_tag(@article.image.url) if @article.image && @article.image.url %></p>
  <p>タイトル:<%= @article.title %></p>
  <p>本文:<%= @article.content %></p>
  <%= f.submit  "登録する" %>
  <%= f.submit "戻る", name: "back" %>
<% end %>

app/views/articles/edit.html.erb
<h2>記事編集</h2>

<%= render 'form'%>

app/views/articles/index.html.erb
<h1>記事一覧</h1>

<table>
  <tr>
    <th>記事種類</th>
    <th>投稿者</th>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.type %></td>
    <td><%= article.user.name %></td>
    <td><%= article.title %></td>
    <td><%= article.content %></td>
    <td><%= link_to '詳細', article_path(article.id) %></td>
    <td><%= link_to "編集", edit_article_path(article.id) %></td>
    <td><%= link_to '削除', article_path(article.id), method: :delete, data: { confirm: "本当に削除しても良いですか？" } %></td>
  </tr>
<% end %>
</table>
<%= link_to '記事新規投稿', new_article_path %>

app/views/articles/new.html.erb
<h2>記事新規作成</h2>

<%= render 'form'%>

app/views/articles/show.html.erb
<h1>記事詳細画面</h1>

<div class="like-link" id="like-link-<%= @article.id %>">
  <%= render partial: 'likes/like', locals: {article: @article, like: @like} %>
</div>

<% if user_signed_in? %>
  <% unless @article.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入り', favorites_path(article_id: @article.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
<% end %>
<span class="favorite_count"><%= @article.favorites.count %></span>

<p>記事種類： <%= @article.type %><p>
<p>
  <strong>Image:</strong>
  <%= image_tag @article.image.url %>
</p>
<p>タイトル: <%= @article.title %></p>
<p>内容: <%= @article.content %></p>
<%= link_to 'ブログ一覧画面に戻る', articles_path %>

app/views/favorites/index.html.erb
<h1>お気に入り記事・質問一覧</h1>

<table>
  <tr>
    <th>記事種類</th>
    <th>投稿者</th>
    <th>写真</th>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr>
    <td><%= favorite.type %></td>
    <td><%= favorite.user.name %></td>
    <td><%= image_tag favorite.image.url %>
    <td><%= favorite.title %></td>
    <td><%= favorite.content %></td>
    <td><%= link_to '詳細', article_path(favorite.id) %></td>
  </tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Katekate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <%= link_to "最新投稿一覧", articles_path %>
      <%= link_to "マイページ", user_path(current_user.id) %>
    <% else %>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>

    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.likes.find_by(article_id: @article.id) %>
    <%= link_to article_like_path(@article.id, current_user.likes.find_by(article_id: @article.id)), method: :DELETE, remote: true do %>
      <div class="iine__button">❤️<%= @article.likes.count %></div>
    <% end %>
  <% else %>
    <%= link_to article_likes_path(@article.id), method: :POST, remote: true do %>
      <div class="iine__button">♡<%= @article.likes.count %></div>
    <% end %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
<%# $('#like_#{@article.id}').html("#{escape_javascript(render "likes/like", article: @article )}"); %>
$('#like-link-<%= @article.id %>').html("<%= j(render partial: 'likes/like', locals: { article: @article, like: @like }) %>");

app/views/likes/destroy.js.erb
<%# $('#like_#{@article.id}').html("#{escape_javascript(render "likes/like", article: @article )}"); %>
$('#like-link-<%= @article.id %>').html("<%= j(render partial: 'likes/like', locals: { article: @article }) %>");

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<% if @user.image? %>
  <%= image_tag @user.image.url %>
<% else %>
  <%= image_tag (asset_path'no_image.png') %>
<% end %>
<h3><%= @user.name %></h3>
<p><%= @user.prefectures %></p>
<p><%= @user_age %>代</p>
<p><%= @user.sex %></p>
<p>自己紹介<%= @user.introduction %></p>

<p>Twitter<%= @user.twitter_url %></p>
<p>Instagram<%= @user.instagram_url %></p>
<p>Tiktok<%= @user.tiktok_url %></p>
<p>Facebook<%= @user.facebook_url %></p>
<p>YouTube<%= @user.youtube_url %></p>
<p>Website<%= @user.website_url %></p>

<%= link_to "プロフィール編集", edit_user_registration_path(@user) %> |
<%= link_to "お気に入り一覧", favorites_path(@user) %>

<table>
  <tr>
    <th>記事種類</th>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.type %></td>
    <td><%= article.title %></td>
    <td><%= article.content %></td>
    <td><%= link_to '詳細', article_path(article.id) %></td>
    <td><%= link_to "編集", edit_article_path(article.id) %></td>
    <td><%= link_to '削除', article_path(article.id), method: :delete, data: { confirm: "本当に削除しても良いですか？" } %></td>
  </tr>
<% end %>
</table>